# -*- coding: utf-8 -*-
"""Economics Times  Scraping assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6U9UlzVPNQ6glpAbErCDhXDFG3ZtT8i
"""

pip install bs4

pip install requests

import bs4
from bs4 import BeautifulSoup
import requests

url = "https://economictimes.indiatimes.com/markets/stocks/news"

headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
}

r = requests.get(url, {'headers':headers})

r.content

soup = rbs4.BeautifulSoup(r.text, 'html.parser')

soup.find_all()

soup.find_all('div')

"""soup.find_all('div',{'class':'eachStory'})"""

soup.find_all('div',{'class':'eachStory'})[0].find('span')

for i in range (7):

   print(f"\n{soup.find_all('div',{'class':'eachStory'})[i].find('p').text}")

for i in range (7):
 print(f"\n{soup.find_all('div',{'class':'eachStory'})[i].find('h3').text}")