# -*- coding: utf-8 -*-
"""Facebookdsbda1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN3QpITrZ8hJqeabZvXu1Wapf0Nx-84j
"""

import numpy as np

import pandas as pd

from google.colab import drive
drive.mount("/content/drive")

df = pd.read_csv("/content/drive/MyDrive/dataset_Facebook.csv",sep=';')
df

df.tail(10)

df.head(15)

df.info()

df.describe()

df.shape

sample = df.loc[10:20]
sample

temp = df[['Type','comment','Post Month']].loc[1:50]
temp

df1 = df[['Category','Type','comment','Post Month']].loc[10:50]
df2 = df[['Category','Paid','like','Type']].loc[51:100]
df3 = df[['Category','comment','Total Interactions','like']].loc[101:150]
df4 = df[['Category','share','Page total likes','Post Month']].loc[151:200]

df2

df3

df1

df4

mergedf = pd.concat([df1,df2,df3,df4])
mergedf

sort_values=mergedf.sort_values(['Type','Paid','like'],ascending=False)
sort_values

sortdf4 = df4.sort_values(['Page total likes'],ascending=False)
sortdf4

mergedf.transpose()

mergedf.shape

arr = np.array([20,30,40,50,60,70,80,90,100,120,110,140])

r_arr = arr.reshape(3,4)

r_arr

r_arr = arr.reshape(-1)
r_arr

newarray = np.array(mergedf)
newarray

newarray.shape

newarray.reshape(-1)

newarray.reshape(191, 9)



















































































































































































